### ISSUE TITLE
Missing omht.jar file.

### ISSUE THREAD

**Issue by Rajratnpranesh** [agroportal/ontology_mapping_harvester#26]
Thank for open sourcing your work. I am trying to implement the code and see the working for mapping task as described in the research paper- "AgroPortal: A vocabulary and ontology repository for agronomy".

As mentioned in the README to start working I have to download 'omht.jar' file. I am not able to find the file in the repository. Can you please specify from where I can exactly download it.

Thank you.

**Comment by elcioabrahao** [comment]
Hi Mr. Rajratnpranesh,
I ´m not in charge of this project anymore. Please refer to the project curator Mr. Clement Jonquet: jonquet@lirmm.fr 
Best regards,
Elcio A., PhD

**Comment by Rajratnpranesh** [comment]
Okay, I will contact him.
Thanks.

**Comment by amirlad** [comment]
Hi Mr. Rajratnpranesh,

You should clone the project to your workspace and generate the jar file from there.

Then, you need to create an account on AgroPortal and BioPortal. You will use the generated API keys by the two platforms in order to set up the jar file. Please follow the documentation in here to have a better idea: https://github.com/agroportal/ontology_mapping_harvester
I hope this helps you. 

If you need any further special assistance, please let me know.
 
Regards,
Amir L. ,P.hD. 
Agroportal Team

**Comment by Rajratnpranesh** [comment]
Dear Amirlad,

Thank you for your reply. I have cloned the project in my workspace. Regarding the jar file generation. I am trying to create a jar file through the command prompt. Since the .java files are in different folders, can you please tell me which files I should include while making the jar file.

Regards,
Raj

**Comment by amirlad** [comment]
Hi.

I recommend to use  this IDE ( .https://www.jetbrains.com/idea/ ) to open OMHT and generate the jar file 

Regards,
Amir L. ,P.hD.
Agroportal Team
